### Post Data
POST http://localhost:5001/orders
Content-Type: application/json

{
  "userId": "68baa248830dbbb1ce463ce0",
  "services": [
    {
      "serviceType": "ตามชิ้น",
      "details": {
        "description": "คำสั่งซื้อตามชิ้นทั่วไป"
      }
    }
  ],
  "items": [
    {
      "name": "เสื้อเชิ๊ต2",
      "quantity": 3,
      "price": 25
    },
    {
      "name": "กางเกงขายาว2",
      "quantity": 1,
      "price": 50
    }
  ],
  "notes": "ไม่ใช้สารฟอกขาว",
  "amount": 150,
  "pickupDate": "2025-09-10T10:00:00Z"
}

### Get
GET http://localhost:5001/orders/68baa248830dbbb1ce463ce0

### Delete
DELETE http://localhost:5001/orders/68bf97b8b171c4dbc942a0d1

### Search
GET http://localhost:5001/orders/search?userId=68baa248830dbbb1ce463ce0&query=กางเกงขายาว

### Edit status
PUT http://localhost:5001/orders/68bf1af3dc21bbbbefff9254/status
Content-Type: application/json

{
    "orderStatus": "Processing"
}