### Post Data
POST http://localhost:5001/orders
Content-Type: application/json

{
  "user_id": "y64152fwse54s12dhyq5r", 
  "order_date": "2025-03-09",
  "service_id": " 51e2dstw5rds52sdy",
  "service_items" : [
  { item_id:"2341345fsgh", quantity:1 },
  { item_id:"123456fsgh", quantity:1 },
  { item_id:"35799fsgh", quantity:1 },
  ]
  "pickup_date": "2025-03-09",
  "pickup_time": "12.00-13.00",
  "note": "รบกวนไม่ใส่ไฮเตอร์ผ้าขาว",
  "order_status": "pending",
  "payment_status": "success",
  "delivery_date": "2025-03-10",
  "order_amount": 500,
}

### Get
GET http://localhost:5001/orders/68baa248830dbbb1ce463ce0

### Delete
DELETE http://localhost:5001/orders/68bf97b8b171c4dbc942a0d1

### Search
GET http://localhost:5001/orders/search?userId=68baa248830dbbb1ce463ce0&query=กางเกงขายาว

### Edit status
PUT http://localhost:5001/orders/68bf1af3dc21bbbbefff9254/status
Content-Type: application/json

{
    "orderStatus": "Processing"
}