### Post Data
POST http://localhost:5001/orders
Content-Type: application/json

{
  "userId": "68baa248830dbbb1ce463ce0",
  "createOn": "2025-03-09",
  "services_id" : "68c7c3fb6ecad34a124adfc1",
  "service_items" : [
    { "items_id":"68c7c4266ecad34a124adfc4", "quantity": 1 }
  ],
  "pickup_date": "2025-03-09",
  "pickup_time": "12.00-13.00",
  "notes": "รบกวนไม่ใส่ผงซักฟอกขาว",
  "order_status": "Pending",
  "amount": 500,
  "delivery_date": "2025-03-10",
  "payment_status": "Paid"
}

### Get
GET http://localhost:5001/orders/68baa248830dbbb1ce463ce0

### Delete
DELETE http://localhost:5001/orders/68c7ca8cd0569f77ccfdb035

### Search
GET http://localhost:5001/orders/search?userId=68baa248830dbbb1ce463ce0&query=กางเกงขายาว

### Edit status
PUT http://localhost:5001/orders/68bf1af3dc21bbbbefff9254/status
Content-Type: application/json

{
    "orderStatus": "Processing"
}